### ISSUE TITLE
Dockerize MyUom proposal

### ISSUE THREAD

**Issue by vdr14** [Open-Source-UoM/MyUoM#1]
## Περιγραφή
Το docker είναι ένας τρόπος να βάλει κάποιος την εφαρμογή σε containers. Τα containers έχουν πολλά θετικά άλλα κυρίως είναι πως θα διευκολύνει το deployment και το development διότι σηκώνει δικό του "λειτουργικό" από κάτω με όλα τα απαραίτητα dependencies ενώ παράλληλα μοιράζεται τον πυρήνα του λειτουργικού (δηλαδή είναι ελαφρύ). Δεν θα χρειαστεί ο developer η ο server admin να κάνει setup το περιβάλλον για να δοκιμάσει την εφαρμογή και θα διευκολυνθεί κάποιος που θέλει να το κάνει fork.

### Τι προτείνω
Θα ήθελα αν είστε ανοιχτοί σε αυτό να κάνω dockerize (με ένα dockerfile η αν έχετε κάποια άλλη προτίμηση) την εφαρμογή αυτή και να κάνω της απαραίτητες αλλαγές / προσθέσεις στο documentation για το docker.

### Τι θα χρειαστώ
Αν έχετε κάνει κάποιο πλάνο ήδη και μπορείτε να το μοιραστείτε θα ήταν ευπρόσδεκτο για να υλοποιήσω. Θα χρειαστώ επίσης την έκδοση node js που χρησιμοποιείτε αν και η 21 φαίνεται να δουλεύει κανονικά.

**Comment by GeorgeFkd** [comment]
Το docker ήταν κάτι που θέλαμε να κάνουμε ούτως ή άλλως, οπότε εννοείται κάντο, ιδανικά σε docker-compose και ακόμη καλύτερα αν το έκανες να τρέχει και ένα άδειο java backend σε spring boot ώστε στο μέλλον να μπορεί να επεκταθεί (αν χρειαστείς βοήθεια στείλε εδώ).

Όταν κάνεις το pull request βάλε reviewer @jasonthird ώστε να ελέγξει τι έχεις κάνει.

**Comment by vdr14** [comment]
Για να το κάνω με docker compose θα χρειαστεί να αλλάξω λίγο το folder structure ώστε να χωριστή το app σε διάφορα services. Δηλαδή το node σε ένα docker και ο server η και πρόσθετα backends αλλο docker που θα τα διαχειρίζεται το docker compose.
Αντί για apache είναι ο nginx ok;

Σκέφτομαι να μεταφέρω τον nodejs κωδικά σε ενά νέο app folder και θα φτιάξω ένα nginx folder οπού θα έχει της ρυθμίσεις του nginx server. Μετά από αυτό το empty java back end που ζητάτε θα μπορείτε να το προσθέσετε εσείς όταν χρειαστεί στο μέλλον όπως θα προσθέσω το nginx.

**Comment by jasonthird** [comment]
Nginx είναι οκ. Όσο για το folder restructuring αν το θεωρείς αναγκαίο για το dockerization κάντο απλά πρόσεχε στο .gitignore και documentation να ανανεωθεί αντίστοιχα

**Comment by vdr14** [comment]
@jasonthird 
έκανα το pull request

**Comment by jasonthird** [comment]
Έχεις ένα μικρό θέμα με το node js, φαίνεται ο server να ξεκινά σε development mode. Αν μπορείς κάντο να ξεκινά σε production mode

**Comment by vdr14** [comment]
Ευχαριστώ για το feedback, τώρα ο nginx server αναλαμβάνει όλο serving του app, είχα ξεχάσει να το αλλάξω

**Comment by jasonthird** [comment]
Αν και φαίνεται να δουλεύει μετά από συζήτηση που κάναμε δεν θεωρούμε καλό το folder restructuring και δεν είναι απαραίτητο. Μπορείς απλά να βάλεις το nginx folder στο .dockeringore του node και δεν θα χρειαστεί να βάλεις το node σε καινούργιο app folder

**Comment by vdr14** [comment]
Καταλαβαίνω, όντως τώρα που το ξανακοιτάω δεν είναι απαραίτητη η ξεχωριστή φάκελοι

Τα άλλαξα στα τελευταία μου commit με βάση το feedback σας
