### ISSUE TITLE
Under the "Development Team Members" in "About" section, add a "Thank you to all Contributors" section

### ISSUE THREAD

**Issue by GeorgeApos** [open-source-uom/myuom#105]
Under the "Development Team Members" in "About" section, add a "Thank you to all Contributors" section in order to mention all the people who contributed to the project.

We should make it like the members above ( same style ) and retrieve the data from the GitHub API.

Let's have a discussion here on how we can make this possible.

**Comment by shivam-sharma7** [comment]
@GeorgeApos I want to work on this, I think here you want say that we should do it as team members

**Comment by shivam-sharma7** [comment]
and you want to show same data as - https://github.com/open-source-uom/myuom/blob/84bd38ecbbb3ac4d198acfef346cab70324f387f/src/assets/data/projectMembers.js#L41

**Comment by shivam-sharma7** [comment]
Look at the preview below, I think its would be better if i am getting your thoughts

![image](https://github.com/open-source-uom/myuom/assets/91419219/b519333f-b531-4b51-b2a9-29b7be124507)

**Comment by shivam-sharma7** [comment]
@GeorgeApos @Tsalmas-Anastasios  I have done it, I need your thought

![image](https://github.com/open-source-uom/myuom/assets/91419219/c2e29061-1289-4e27-a7c8-855032c9ca20)

**Comment by GeorgeApos** [comment]
@shivam-sharma7 I like it, but what links are you going to add in each contributor?

**Comment by shivam-sharma7** [comment]
@GeorgeApos I have added three links like email, linkedin and Github

**Comment by shivam-sharma7** [comment]
Give a Quick look

![image](https://github.com/open-source-uom/myuom/assets/91419219/941f9e1c-be54-4800-aedb-372335bd4a1a)

**Comment by GeorgeApos** [comment]
Are you entering them manually? I was thinking maybe just communicating with the GitHub API because there won't be too many people making changes once in a while

**Comment by shivam-sharma7** [comment]
@GeorgeApos No, I have look at github contributors section and add these contributors yet, You can suggest who should i add.

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 Use the GitHub API and include their GitHub profile. If you can check the social media links of every contributor that would be ideal, but we can't do it manually by looking at the section.

@GeorgeApos does 'Development Team Members' follow GitHub API ? If so then I have done it exactly

**Comment by GeorgeApos** [comment]
No it doesn;t ... anyway send us the PR and we will discuss about it there. @shivam-sharma7

**Comment by shivam-sharma7** [comment]
@GeorgeApos check now i have send
