### ISSUE TITLE
Enforce normalization of line ending to LF

### ISSUE THREAD

**Issue by shivam-sharma7** [open-source-uom/myuom#21]
Get Consistent Line Breaks in VS Code for Windows. Unix systems (Linux and Mac) default to the LF (line feed) character for line breaks. Windows on the other hand is “special” and defaults to CRLF

Describe alternatives you've considered
we can use this-https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings

**Comment by GeorgeApos** [comment]
I'll move this to the backlog for now as we require further information and discussion on the approach for implementation.

**Comment by shivam-sharma7** [comment]
@GeorgeApos it will take 10-15 line of code
