### ISSUE TITLE
Add some margin from bottom

### ISSUE THREAD

**Issue by shivam-sharma7** [open-source-uom/myuom#34]
![image](https://github.com/Open-Source-UoM/MyUoM/assets/91419219/7232dbdc-9700-4e68-9b17-ac07ed631ebe)

**Comment by GDGouravDey** [comment]
I do not exactly understand what is the issue here. Is the issue saying to increase the value of margin below the change language and flag section? 
The current value of margin-bottom is set to 0.5rem, in that case I can change it to 1rem for a better result.

**Comment by GDGouravDey** [comment]
#38 This PR fixes this issue.

**Comment by GDGouravDey** [comment]
Thinking this issue was an easy fix, I made the changes and did PR. I should have taken consideration of your permission first. I apologise for any inconvenience caused. Will seek permission from now on.

I am closing the PR. Looking forward to work in a collaborative way to enhance the project.

**Comment by kash2104** [comment]
Can I work on this issue?

**Comment by shivam-sharma7** [comment]
@kash2104 Sorry, Look for another

**Comment by NikolasPpd** [comment]
If you're referring to the `g`'s being cut off, this isn't really the case. That's just the design of the letter in the font we're using. You can have a look here https://fonts.google.com/specimen/Syne

**Comment by shivam-sharma7** [comment]
@GeorgeApos I agree with @NikolasPpd this is font then what do you think?

**Comment by GeorgeApos** [comment]
Yeah that's true. You can see also the manual where we use Syne or look at another g's in the application.

I am closing the issue.
