### ISSUE TITLE
Blocked / Inactive Tiles cannot be Distinguised from Active Tiles in Dark Theme

### ISSUE THREAD

**Issue by GDGouravDey** [open-source-uom/myuom#40]
- In Dark Theme, the Blocked / Inactive Tiles cannot be distinguished from Active Tiles. [ Barely Distinguishable ]
- User may be confused and unable to differentiate between Active and Inactive Tiles.
- This issue only occurs when User have not already chosen the Department.

Issue Image : -

![ui](https://github.com/open-source-uom/myuom/assets/117531461/3ea1e6f7-1165-463d-a4cb-19a6310d780f)
![ui](https://github.com/open-source-uom/myuom/assets/117531461/99646831-ee32-480f-81da-133a4e83e3c8)

**Comment by turjoc120** [comment]
what do you suggest? try giving it a slightly gray color might be helpful, 

are you going to work on this soon, or can I take care of it?

![Screenshot 2024-03-02 075146](https://github.com/open-source-uom/myuom/assets/86681794/8edf2743-67c3-478b-81f3-76fadb0bb79c)

**Comment by GDGouravDey** [comment]
I am currently working on it. This is the same approach I am taking. If I do not complete it in 1-2 days, you may send a PR on this issue.

**Comment by GDGouravDey** [comment]
#42 This PR solves this Issue.
