### ISSUE TITLE
Integrate Playwright for end-to-end Test

### ISSUE THREAD

**Issue by shivam-sharma7** [open-source-uom/myuom#48]
check-https://playwright.dev/

**Comment by sankalpie** [comment]
Greetings @shivam-sharma7 
I am willing to contribute to this issue. For doing so, I have initiated Playwright, made the initial setup. 
If possible, can you provide some examples of actions along with their state expectations.
More tests can be added as required.

**Comment by shivam-sharma7** [comment]
@sankalpie please, All issue that created by me its part of plan and I will do that so look anothers

**Comment by GeorgeFkd** [comment]
I will write up some documentation regarding the testing of this application, manual at first and written in detail, and then we can go ahead and automate it.

**Comment by GeorgeFkd** [comment]
Here i have started writing the [Testing Documentation][(https://github.com/open-source-uom/myuom/docs/testing.md](https://github.com/open-source-uom/myuom/blob/main/docs/testing.md).
We can keep the discussion going here taking into account the above document and suggesting changes.
