### ISSUE TITLE
Professor's title doesn't shown correct in Professors Page

### ISSUE THREAD

**Issue by kyriakid1s** [open-source-uom/myuom#68]
While exploring the professors page I found that each professor's title is shown incorrectly. 
The issue is shown in the image below.
<img width="1440" alt="Screenshot 2024-03-19 at 8 21 57 PM" src="https://github.com/open-source-uom/myuom/assets/24926750/ea55ff17-b3c9-494d-8b06-53fc62a30fc0">

**Comment by kyriakid1s** [comment]
Professor's title is "kathigitis", while it has be professor. It isn't translated.

**Comment by GeorgeApos** [comment]
Excellent, thank you!
