### ISSUE TITLE
Professors' names are not translated and they aren't capitalize

### ISSUE THREAD

**Issue by kyriakid1s** [open-source-uom/myuom#70]
Professors' names are always in English and lowercase as shown in the following images
1. Greek
<img width="1440" alt="Screenshot 2024-03-20 at 6 05 28 PM" src="https://github.com/open-source-uom/myuom/assets/24926750/f6b15fdc-b3e6-433a-9772-83f00374dc2d">
2. English
<img width="1440" alt="Screenshot 2024-03-20 at 6 05 47 PM" src="https://github.com/open-source-uom/myuom/assets/24926750/da9db8f9-039f-4951-8e88-dab860e0fb8d">

**Comment by kyriakid1s** [comment]
Is this project dead ?

**Comment by GeorgeApos** [comment]
No, but unfortunately we are all working, and we do not have the time to immediately check all the pull requests.
