### ISSUE TITLE
CI: Add node.js github action

### ISSUE THREAD

**Issue by shivam-sharma7** [open-source-uom/myuom#8]
Add CI/CD feature for fast build, test and deploy application

**Comment by GeorgeApos** [comment]
The challenge with implementing CI/CD for our project is the absence of a dedicated server for deployment. Currently, we're utilizing Cpanel for hosting, which poses significant limitations for our application. Transitioning to a standalone application or migrating to a new server would resolve this issue seamlessly.

**Comment by shivam-sharma7** [comment]
I have renamed this we will be looking CD part in different issue, I hope sound make sense
