### ISSUE TITLE
Wrong redirection links when application's language is English

### ISSUE THREAD

**Issue by giomellios** [open-source-uom/myuom#80]
When the language of the application is English, all the redirection links refer to the Greek version of each Department.
Example: 
(Department selected is Applied Informatics)

When clicking on Student Care:
![image](https://github.com/open-source-uom/myuom/assets/82503972/ec2a8625-dec1-424e-b4a2-806b6b50450c)

User gets redirected to:
![image](https://github.com/open-source-uom/myuom/assets/82503972/33c65664-21dc-48a4-b601-1997faa49267)
Which is the Greek version of student care.

Instead, users should be redirected to the English version of the Department's website. 
The same rule applies to any redirection where an English version is available on the Department's website.

**Comment by GeorgeApos** [comment]
I see, can you fix that? @giomellios

**Comment by giomellios** [comment]
I will fit it into my schedule and handle it as soon as I can.

**Comment by NikolasPpd** [comment]
If a resource is not available in English why not just send them to the Greek version instead?

It's not ideal, but I'd rather have a resource in a language that I don't understand and which I can probably translate and make some sense of, than being redirected to a 404 page that essentially tells me the info I'm looking for does not exist at all.
