### ISSUE TITLE
Add dependabot to manage node dependencies versions

### ISSUE THREAD

**Issue by shivam-sharma7** [open-source-uom/myuom#9]
See- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#example-of-a-basic-setup-for-three-package-managers

**Comment by GeorgeApos** [comment]
I'm enthusiastic about this idea and fully support its implementation in upcoming versions. That's why I'm assigning it a low priority for now.
